stages:
  - test
  - deploy

image: node:10

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

before_script:
  - npm install --no-save

typecheck:
  stage: test
  script: npm run typecheck

lint:
  stage: test
  script: npm run lint

build:
  stage: deploy
  # only:
  #   - master
  script:
    - npm run build
